### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by liuguilin1225** [swift-n-brutal/syntex#1]
Thanks for the interesting work and sharing the code. Is it possible to share the pretrained model?

**Comment by swift-n-brutal** [comment]
The model for the floral dataset provided in this repo can be found in [OneDrive](https://mycuhk-my.sharepoint.com/:f:/g/personal/1155067722_link_cuhk_edu_hk/EoxkZ_KUcmxMjjowIBdXm3kB49dWTgxl7oBF_sU8zNSQag?e=snFUvT). This model is for illustration purposes. You can follow the test instruction (using improved_model.py) to produce the results (like Fig. 6) of ProPO.
