### ISSUE TITLE
The SynTEX database question

### ISSUE THREAD

**Issue by TianheWu** [swift-n-brutal/syntex#2]
Hi, can you share the SynTEX database downloading link? The original link is not work.
Thanks!

**Comment by swift-n-brutal** [comment]
> Hi, can you share the SynTEX database downloading link? The original link is not work. Thanks!

Do you mean the datasets or the pretrained models? The floral and DTD datasets are available from their original sources. I don't think it is proper to store the data in this repo. For the models, I highly recommend training the model on your own images. It takes ~5 days to get quite good results using only one GPU.

**Comment by TianheWu** [comment]
Thanks, can you share the original sources? I can not open it....

**Comment by swift-n-brutal** [comment]
> Thanks, can you share the original sources? I can not open it....

The floral dataset is in this [folder](https://github.com/swift-n-brutal/syntex/tree/master/images). You can simply clone this repo. I don't have the images of DTD right now. You can download it from [here](https://www.robots.ox.ac.uk/~vgg/data/dtd/) or search on the internet for other sources.
